### ISSUE TITLE
How to implement my own wifidog-auth?

### ISSUE THREAD

**Issue by moontide** [wifidog/wifidog-auth#4]
Hi,

Sorry for posting here, I don't know where to ask (mailing list is dead, nobody in IRC channel), consider this is a feature request for  document.

I want to implement my our own wifidog-auth which can
- authenticate via LDAP (only staffs can access the WIFI access point, I know FreeRADIUS server has this feature, but I want to implement the following features too)
- authenticate via phone extension (yeah, when user click login, my own wifidog-auth will try to call extension number of this staff: [my own wifi-auth running on an Asterisk server]->[create a .call file for Asterisk]->[call to staff's extension and put this call into an IVR], and then the staff must enter his/her phone password to authenticate)
- authenticate via mobile phone SMS (we have a SMS api provided by a SP. before login, user must retrieve a random code to his mobile phone, then input that random code as password to authenticate)

I can write the web stuffs (JSP), but I don't know how to communicate with wifi-gateway: What/How should I return to the gateway if login is sucessful or failed?

**Comment by acv** [comment]
The protocol is described here: http://dev.wifidog.org/wiki/doc/developer/WiFiDogProtocol_V1

It's really fairly simple.

**Comment by moontide** [comment]
Thanks for the document link!
Although I've setup basic WPA2-EAP(WPA2-Enterprise/WPA2-RADIUS) authentication/encryption, I still want to implement web-based authentication (just for fun).

**Comment by sgaseretto** [comment]
moontide, have you succesfully implement the web-based authentication server?

**Comment by moontide** [comment]
@sgaseretto 
Sorry, I didn't.

**Comment by dastathagata** [comment]
moontide, could you please me how did you set up authentication server for WiFidog? I have been facing lots of issue in doing that.  I followed the steps mentioned in http://dev.wifidog.org/wiki/doc/install/auth-server
